[package]
name = "viewer"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.35.*"
vulkano-win = "0.34.*"
vulkano-shaders = "0.35.*"
ash = "0.38.0" # For some minor functionality not covered by vulkano
winit = "0.30.11" # Apparantly has to be hardcoded to same version vulkano-win uses
glam = { version = "0.30.5", features = ["debug-glam-assert"] }
uuid = { version = "1.17.0", features = ["v8"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.174"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = ["Win32_System_Diagnostics_ToolHelp", "Win32_System_Threading"] }
