# Thanks to xKiraiChan for this workflow file (https://github.com/xKiraiChan/CVRPlugins)

name: publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Unity
        id: cache-unity
        uses: actions/cache@v3
        with:
          path: Unity
          key: ${{ runner.os }}-unity

      - name: Setup Unity
        id: setup-unity
        if: steps.cache-unity.outputs.cache-hit != 'true'
        uses: kuler90/setup-unity@v1
        with:
          install-path: Unity
          unity-version: 2019.4.31f1

      # Copied from ./res/bundleassets
      - name: Build assetbundles
        run: ${{ steps.setup-unity.outputs.unity-path }} -quit -batchmode -nographics -executeMethod BuildAssetBundlesEditorScript.BuildAssetBundles -projectPath $GITHUB_WORKSPACE/res || exit 0

      - name: Setup.NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Build_$(date +"%Y.%m.%d_%H-%M")"
      
      - name: Publish a release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: src/*/bin/Release/netstandard2.1/*.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}